name: only_click
description: A new Flutter project.
publish_to: 'none' # Prevents accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  get_storage: ^2.1.1
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  animate_do: ^3.3.4
  simple_animations: ^5.0.2
  scrollable_positioned_list: ^0.3.8
  cached_network_image: ^3.3.1
  intl_phone_field: ^3.2.0
  carousel_slider: ^4.2.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  flutter_chat_ui: ^1.6.14
  flutter_chat_types: ^3.6.2
  open_filex: ^4.4.0
  file_picker: ^8.0.5
  http: ^1.2.1
  mime: ^1.0.5
  path_provider: ^2.1.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl: ^0.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/icons/categories/
    - assets/icons/mostbooked/
    - assets/images/
    - assets/images/banners/
    - assets/images/Sel_lan/
    - assets/images/OnBoarding/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Font/Montserrat-Bold.ttf
    - family: Poppins
      fonts:
        - asset: assets/Font/Poppins-Light.ttf
          weight: 300
        - asset: assets/Font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/Font/Poppins-Italic.ttf
          style: italic
        - asset: assets/Font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/Font/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/Font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/Font/Poppins-Bold.ttf
          weight: 800
    - family: Raleway
      fonts:
        - asset: assets/Font/Raleway-Light.ttf
          weight: 300
        - asset: assets/Font/Raleway-Regular.ttf
          weight: 400
        - asset: assets/Font/Raleway-Medium.ttf
          weight: 500
        - asset: assets/Font/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/Font/Raleway-Bold.ttf
          weight: 800
